/* HubSpot Certified Trainer.

   Written from HubSpot Academy's published course outline and the program
   policies page, not from exam questions. Every item here is original and
   drills a stated objective rather than reproducing anything from the real
   paper.

   Two things about this certification that the exam itself does not test but
   which decide whether you actually get certified:
     - You must be accepted as a HubSpot trainer before the exam is available.
     - The exam is only half of it. The practicum workbook is submitted for
       review and graded within seven business days, and it is the real gate.
   Both are in the practicum checklist below.

   Domain weightings are inferred from the relative depth of the published
   lessons; HubSpot does not publish a numeric blueprint for this exam. */

window.CERT_COURSES.push({
  id: "hubspot-trainer",
  built: "2026-08-02",
  cert: {
    code: "HST",
    name: "HubSpot Certified Trainer",
    vendor: "HubSpot Academy",
    blurb: "Training fundamentals, content design, delivery and running training as a service. Exam plus a graded practicum workbook.",
  },
  exam: {
    questionCount: 60,
    timeLimitMin: 180,
    passMode: "raw",
    passValue: 45,
    scaledMax: 0,
    multiSelect: false,
    note: "60 questions, 45 correct to pass. 3-hour limit, ~1 hour expected. 12-hour lockout between attempts.",
  },

  domains: [
    {
      id: "fund",
      name: "Training Fundamentals",
      weight: 0.18,
      summary: "Why training exists as a discipline, how adults actually learn, and what separates a trainer from a presenter. The conceptual base the rest of the exam builds on.",
      keyPoints: [
        "Training changes behaviour; presenting transfers information. If nobody does anything differently afterwards, it was a presentation.",
        "Adults learn from problems they already have, not from curricula. Relevance to today's work beats logical topic order.",
        "Learning objectives are written as observable learner behaviour: 'create a workflow', not 'understand workflows'.",
        "The forgetting curve is steep. Spacing, retrieval practice and application beat a single longer session.",
        "Learners need to do the thing during the session, not after it. Watching a demo is not practice.",
        "Psychological safety comes first: people who are worried about looking incompetent do not ask the question they need answered.",
        "Know the difference between training (build capability), enablement (sustain it) and support (unblock it). They need different formats.",
        "Every session has a business reason. If you cannot name the metric it moves, you cannot show it worked.",
      ],
      objectives: [
        "Distinguish training from presenting, enablement and support",
        "Apply adult learning principles to session design",
        "Write observable learning objectives",
        "Explain why practice and spacing beat exposure",
      ],
    },
    {
      id: "prep",
      name: "Preparing and Planning",
      weight: 0.22,
      summary: "The work before any content exists: understanding the audience, diagnosing the real need, agreeing what success looks like, and scoping a session that fits the time available.",
      keyPoints: [
        "Preparing is not creating. Preparing is finding out who is in the room and what they need; creating is building materials for what you found.",
        "Start from the business problem, not the feature list. 'Reps are not logging calls' is a brief; 'train them on Sales Hub' is not.",
        "Audience analysis covers role, current skill level, what they already use, and what they are afraid of.",
        "Agree success criteria with the stakeholder before you build anything, in writing.",
        "A needs assessment often concludes that training is the wrong intervention — a broken process or missing permission cannot be trained away.",
        "Scope to the time you have. Cutting content late produces a rushed ending; scoping early produces a complete one.",
        "Confirm the logistics that break sessions: room, screens, licences, sandbox access, portal permissions, recording consent.",
        "Always build a fallback for the demo. Live portals go down during exactly the session you cannot repeat.",
        "Pre-work only counts if you can assume it. If half the room will not do it, design as if none of them did.",
      ],
      objectives: [
        "Run an audience and needs analysis",
        "Agree measurable success criteria with a stakeholder",
        "Decide when training is not the right intervention",
        "Scope content to available time and confirm logistics",
      ],
    },
    {
      id: "create",
      name: "Creating Training Content",
      weight: 0.20,
      summary: "Turning an agreed need into materials: structure, exercises, slides, handouts and the practice that makes any of it stick.",
      keyPoints: [
        "Design backwards from the objective: what must they be able to do, what practice proves it, what content is needed to support that practice.",
        "Build the exercise first. Content written before the exercise expands to fill the session and squeezes practice out.",
        "Chunk into 10–15 minute blocks, each ending in something the learner does.",
        "Slides support the talk; they are not the handout. A slide that works as a leave-behind is too dense to present from.",
        "Use the learner's own data and scenarios wherever possible — generic demo data is forgettable.",
        "Job aids and checklists outlive the session and are what people actually use on the Monday after.",
        "Build in a difficulty ramp: a guided example, then a supported one, then an independent one.",
        "Accessibility is design, not an afterthought: contrast, font size, captions, and never colour alone to carry meaning.",
        "Version and date your materials. Product UIs change and stale screenshots destroy credibility fast.",
      ],
      objectives: [
        "Apply backwards design from objectives to content",
        "Structure a session into practice-anchored chunks",
        "Build effective exercises, job aids and slides",
        "Design accessible, maintainable materials",
      ],
    },
    {
      id: "deliver",
      name: "Delivering Training",
      weight: 0.26,
      summary: "The session itself: facilitation, engagement, handling the room, running virtual sessions, dealing with questions you cannot answer and participants who make it hard.",
      keyPoints: [
        "Open by connecting the session to the learner's problem, not by introducing yourself at length.",
        "Check understanding by asking people to do or explain something, never by asking 'does that make sense?'",
        "Silence after a question is normal. Count to five before filling it — the first answer usually arrives at four.",
        "Virtual sessions need an interaction roughly every five minutes: poll, chat prompt, breakout, or a named question.",
        "'I don't know, I'll find out and send it by Friday' protects your credibility. Guessing destroys it.",
        "Park off-topic questions visibly and come back to them. Ignoring them costs you the room.",
        "The dominant participant is managed by structure — round-robins, written first, named turns — not by confrontation.",
        "The disengaged participant is usually a relevance problem or a mandated-attendance problem. Find out which before deciding it is attitude.",
        "Time-check against your plan at fixed points, and cut a planned section rather than compress the practice.",
        "Close with what happens next: the job aid, the follow-up, and who to ask on Monday.",
      ],
      objectives: [
        "Facilitate rather than present",
        "Check understanding and manage time",
        "Run engaging virtual and in-person sessions",
        "Handle difficult questions and difficult participants",
      ],
    },
    {
      id: "impl",
      name: "Implementing Training Services",
      weight: 0.14,
      summary: "Running training as an offering: scoping and pricing engagements, packaging services, measuring outcomes and proving value to the client.",
      keyPoints: [
        "Price the outcome and the preparation, not the hours in the room. Delivery is the visible tip of the work.",
        "Scope in writing: audience, size, objectives, format, materials, revisions, and what is explicitly out of scope.",
        "Kirkpatrick's four levels: reaction, learning, behaviour, results. Most training stops measuring at level one.",
        "A smile sheet measures reaction only. It tells you whether they enjoyed it, not whether anything changed.",
        "Measure behaviour in the system itself — adoption, logged activity, workflow usage — not in a follow-up survey.",
        "Baseline before you train. Without a before, an after proves nothing.",
        "Package training with an adoption plan; one-off sessions decay within weeks without reinforcement.",
        "Recertification and product change mean materials are a maintained asset, not a one-time build.",
      ],
      objectives: [
        "Scope and price a training engagement",
        "Apply the four levels of evaluation",
        "Measure behaviour change rather than satisfaction",
        "Package training as a sustained service",
      ],
    },
  ],

  /* The practicum is the real gate on this certification. */
  tasks: [
    { d: "fund", title: "Confirm you are accepted into the HubSpot trainer program", minutes: 20,
      detail: "The Trainer certification only becomes available once you have been accepted as a HubSpot trainer. Check your Academy account before booking anything else." },
    { d: "fund", title: "Check your prerequisite certifications are current", minutes: 15,
      detail: "Maintaining the Trainer certification commits you to holding Inbound and HubSpot Marketing Software. Renew anything that has lapsed — they expire yearly." },
    { d: "prep", title: "Complete the audience and needs analysis section of the workbook", minutes: 45,
      detail: "Work through the preparation activities against a real or realistic client scenario. Name the business problem, the audience, and the success criteria." },
    { d: "create", title: "Build the training content required by the workbook", minutes: 90,
      detail: "Produce the materials the workbook asks for — session outline, slides, exercise and job aid. Design backwards from your stated objectives." },
    { d: "deliver", title: "Record or run the delivery activity", minutes: 60,
      detail: "Deliver the session the workbook specifies. Watch it back once and note where you filled a silence or checked understanding with a closed question." },
    { d: "impl", title: "Submit the completed practicum for review", minutes: 20,
      detail: "Every activity must be complete. Certification is per person — you cannot submit as a team. Expect a grade within seven business days, so do not leave this to the week you need the credential." },
  ],

  cards: [
    { d: "fund", x: 1, f: "What separates training from presenting?", b: "Training is measured by changed behaviour; presenting by information delivered. If nobody works differently afterwards, it was a presentation." },
    { d: "fund", x: 2, f: "Why do adults learn differently from students?", b: "Adults come with existing experience and an immediate problem. They engage with content that solves something they are dealing with now, not with a logically ordered curriculum." },
    { d: "fund", x: 2, f: "What makes a learning objective usable?", b: "It names an observable learner behaviour — 'build a deal-stage workflow' — so you can tell whether it happened. 'Understand workflows' cannot be observed or assessed." },
    { d: "fund", x: 2, f: "What is the forgetting curve's practical implication?", b: "Most of a single session is lost within days. Spacing, retrieval practice and real application recover far more than lengthening the session would." },
    { d: "fund", x: 3, f: "Training, enablement or support — what is the difference?", b: "Training builds capability, enablement sustains it with tools and reinforcement, support unblocks a specific problem. Using one where another is needed is a common misdiagnosis." },
    { d: "fund", x: 2, f: "Why does psychological safety affect training outcomes?", b: "People who fear looking incompetent do not ask the question they most need answered, so the gap survives the session intact." },
    { d: "fund", x: 3, f: "Why is watching a demo not practice?", b: "Recognition is not recall. Watching produces the feeling of competence without the retrieval that builds it — learners must do the task themselves during the session." },
    { d: "fund", x: 1, f: "What should every session be tied to?", b: "A business reason and a metric it is meant to move. Without one you cannot scope the content or show afterwards that it worked." },
    { d: "fund", x: 2, f: "What does 'learner-centred' actually change in practice?", b: "Design starts from what the learner must be able to do and the problems they arrive with, rather than from the product's feature list or the trainer's expertise." },
    { d: "fund", x: 3, f: "When is training the wrong answer?", b: "When the barrier is process, permissions, tooling or incentives. You cannot train away a missing licence or a workflow nobody is allowed to change." },

    { d: "prep", x: 2, f: "What is the difference between preparing and creating?", b: "Preparing is finding out who is in the room, what they need and what success looks like. Creating is building materials to fit what preparation found. Doing them in the wrong order wastes the build." },
    { d: "prep", x: 2, f: "What belongs in an audience analysis?", b: "Role and daily work, current skill level, what tools they already use, how they were told to attend, and what they are anxious about." },
    { d: "prep", x: 2, f: "Why agree success criteria before building?", b: "It is the only defence against scope creep and the only way to demonstrate value afterwards. Agree them in writing with the stakeholder who asked." },
    { d: "prep", x: 1, f: "What is a needs assessment for?", b: "To establish the gap between current and required performance and to test whether training can close it — sometimes the honest answer is that it cannot." },
    { d: "prep", x: 3, f: "What should you assume about pre-work?", b: "That a meaningful share of the room did not do it. Design the session so it still works, and use pre-work as an advantage rather than a dependency." },
    { d: "prep", x: 2, f: "Why scope to the time available early?", b: "Cutting late produces a rushed ending and a skipped practice section, which is exactly the part that made the session worth running." },
    { d: "prep", x: 2, f: "Which logistics most often break a session?", b: "Portal access and permissions, sandbox data, screen sharing, licences for the tool being taught, and recording consent. Confirm every one before the day." },
    { d: "prep", x: 3, f: "Why prepare a demo fallback?", b: "Live environments fail during exactly the session you cannot reschedule. Screenshots or a recorded walkthrough keep the session running." },
    { d: "prep", x: 2, f: "How does group size change your design?", b: "Small groups support discussion and individual practice; large groups need structured interaction, polls and worked examples, because individual attention does not scale." },
    { d: "prep", x: 2, f: "What question reframes a feature-shaped request?", b: "'What would people be doing differently if this worked?' It converts 'train them on Sales Hub' into an observable behaviour you can design toward." },

    { d: "create", x: 2, f: "What is backwards design?", b: "Start from the objective, decide what practice would prove it, then build only the content that practice needs. It prevents content expanding to fill the session." },
    { d: "create", x: 3, f: "Why build the exercise before the slides?", b: "Content written first expands and squeezes practice out. Building the exercise first fixes the practice time before anything can compete for it." },
    { d: "create", x: 2, f: "How long should a content chunk be?", b: "Roughly 10–15 minutes, each ending in something the learner does. Attention degrades well before that if nothing is asked of them." },
    { d: "create", x: 2, f: "Why should slides not double as the handout?", b: "A slide dense enough to read alone is too dense to present from. Build a separate leave-behind or job aid." },
    { d: "create", x: 1, f: "What is a job aid?", b: "A short reference — checklist, one-pager, decision tree — used at the moment of work. It outlives the session and is what people actually reach for." },
    { d: "create", x: 3, f: "What is the practice difficulty ramp?", b: "Guided worked example, then a supported attempt, then an independent one. Jumping straight to independent practice produces failure rather than learning." },
    { d: "create", x: 2, f: "Why use the learner's own data in exercises?", b: "Their own pipeline, contacts and scenarios are recognisable and transfer directly to Monday. Generic demo data is forgettable and feels irrelevant." },
    { d: "create", x: 2, f: "What are the accessibility basics for materials?", b: "Sufficient contrast, large readable type, captions on video, meaningful alt text, and never using colour alone to carry meaning." },
    { d: "create", x: 3, f: "Why version and date training materials?", b: "Product interfaces change constantly. A stale screenshot in a live session costs you credibility faster than almost anything else." },
    { d: "create", x: 2, f: "How do you decide what to cut?", b: "Cut content, protect practice. Anything that does not serve a stated objective goes first; the exercise is the last thing to lose." },

    { d: "deliver", x: 2, f: "How should you open a session?", b: "By connecting it to the problem the learners have. A long self-introduction spends the most attentive minutes of the session on the least useful content." },
    { d: "deliver", x: 3, f: "Why is 'does that make sense?' a bad check?", b: "It invites a nod. Ask someone to do the step, explain it back, or predict the outcome — a check has to produce evidence." },
    { d: "deliver", x: 2, f: "How long should you wait after asking a question?", b: "About five seconds. Silence feels far longer to the person at the front, and the first real answer usually arrives just after most trainers give up." },
    { d: "deliver", x: 2, f: "How often should a virtual session ask for interaction?", b: "Roughly every five minutes — poll, chat prompt, named question or breakout. Virtual attention decays much faster than in a room." },
    { d: "deliver", x: 1, f: "What do you say when you do not know the answer?", b: "That you do not know, plus when you will come back with it. Guessing in front of a room that can check costs more than the admission." },
    { d: "deliver", x: 2, f: "How do you handle an off-topic question?", b: "Park it visibly — a parking board or shared note — and commit to returning to it. Ignoring it tells the room questions are unwelcome." },
    { d: "deliver", x: 3, f: "How do you manage a dominant participant?", b: "With structure rather than confrontation: round-robins, write-before-share, named turns. Structure redistributes airtime without singling anyone out." },
    { d: "deliver", x: 3, f: "What usually causes disengagement?", b: "Irrelevance or mandated attendance, far more often than attitude. Find out which before treating it as a behaviour problem." },
    { d: "deliver", x: 2, f: "What do you do when you are running late?", b: "Cut a planned content section, not the practice. Compressing the exercise removes the only part that changes behaviour." },
    { d: "deliver", x: 2, f: "How should a session close?", b: "With what happens next: the job aid, the follow-up, the reinforcement, and who to ask on Monday. A summary alone changes nothing." },
    { d: "deliver", x: 3, f: "What is the risk of demoing at full speed?", b: "Expert pace looks effortless and teaches nothing. Narrate what you are clicking and why, and slow to the speed of a first attempt." },
    { d: "deliver", x: 2, f: "Why call on people by name in virtual sessions?", b: "An open question to a muted grid gets silence. A named question gets an answer and signals that participation is expected." },

    { d: "impl", x: 2, f: "What should a training engagement be priced on?", b: "The outcome and the preparation. Delivery hours are the visible tip; analysis, design and materials are most of the work." },
    { d: "impl", x: 2, f: "What belongs in a training scope document?", b: "Audience and size, objectives, format, materials, number of revisions, and an explicit out-of-scope list." },
    { d: "impl", x: 1, f: "What are Kirkpatrick's four levels?", b: "Reaction, learning, behaviour, results — did they like it, did they learn it, are they doing it, did it move the business." },
    { d: "impl", x: 3, f: "Why is a smile sheet insufficient?", b: "It measures level one only. Satisfaction correlates weakly with behaviour change; an enjoyable session can change nothing." },
    { d: "impl", x: 2, f: "Where should behaviour change be measured?", b: "In the system itself — adoption, logged activity, workflow usage, data quality — not in a self-reported follow-up survey." },
    { d: "impl", x: 3, f: "Why baseline before training?", b: "Without a before-measurement an after-measurement proves nothing. The baseline is the only thing that makes the result attributable." },
    { d: "impl", x: 2, f: "Why do one-off sessions decay?", b: "Without reinforcement, job aids and follow-up, new behaviour reverts within weeks. Package an adoption plan alongside the session." },
    { d: "impl", x: 2, f: "What makes training materials an asset rather than a deliverable?", b: "They need maintaining as the product changes. Priced and scheduled as a maintained asset, they stay usable; treated as one-time, they rot." },
  ],

  questions: [
    { d: "fund", x: 2, s: "A client asks you to run a one-hour session so their sales team 'knows about' the new deal pipeline. What is the most useful first response?", c: ["Agree, and build a walkthrough of every pipeline feature", "Ask what the team should be doing differently after the session", "Suggest a two-hour session instead so everything fits", "Send the HubSpot Academy pipeline lesson as pre-work"], a: [1], e: "Reframing to observable behaviour converts a vague awareness request into a designable objective. Building the walkthrough first commits you to content before you know what change is wanted." },
    { d: "fund", x: 2, s: "Which of these is written as a usable learning objective?", c: ["Understand how HubSpot workflows function", "Be familiar with workflow enrolment triggers", "Build a workflow that enrols contacts on form submission", "Appreciate the value of marketing automation"], a: [2], e: "Only 'build a workflow' names something you can watch someone do and therefore assess. Understand, be familiar with and appreciate are all internal states you cannot observe." },
    { d: "fund", x: 3, s: "Reps have been trained twice on logging calls and still do not log them. Investigation shows the call-logging field is not on their record view. What does this indicate?", c: ["The training needs to be more engaging", "A third session with more practice is required", "This is a configuration problem, not a training problem", "The reps need individual coaching"], a: [2], e: "No amount of training closes a gap caused by a missing field. A needs assessment exists precisely to catch cases where the barrier is process or configuration rather than capability." },
    { d: "fund", x: 2, s: "Why is spacing content across two shorter sessions usually better than one long one?", c: ["It is easier to schedule around client calendars", "Retrieval between sessions counteracts the forgetting curve", "Shorter sessions cost less to deliver", "It allows more content to be covered overall"], a: [1], e: "The gap forces retrieval, which is what consolidates learning. Scheduling and cost may also be true but are not the learning reason." },
    { d: "fund", x: 2, s: "A learner says nothing all session, then emails afterwards with a basic question they could have asked in the room. What does this most likely indicate?", c: ["The learner was not paying attention", "The content was pitched too low", "Psychological safety was insufficient", "The session ran over time"], a: [2], e: "Asking a basic question in front of colleagues risks looking incompetent. When people save those questions for private channels, the room did not feel safe enough." },
    { d: "fund", x: 3, s: "A team has been trained and is now performing well, but new starters join monthly and adoption drifts. What does the client actually need next?", c: ["A repeat of the same training session each month", "An enablement approach: job aids, reinforcement and onboarding materials", "Individual support tickets as issues arise", "A longer version of the original training"], a: [1], e: "Training builds initial capability; enablement sustains it. Repeating the session addresses new starters but not drift, and support is reactive rather than preventative." },
    { d: "fund", x: 1, s: "Which best describes the trainer's role during a practice exercise?", c: ["Demonstrating the correct method again at the front", "Circulating, observing and unblocking without taking the keyboard", "Answering questions in the chat while learners work", "Presenting the next section to save time"], a: [1], e: "Practice only works if the learner does the work. Taking over the keyboard or re-demonstrating removes the retrieval that makes practice valuable." },
    { d: "fund", x: 2, s: "What is the strongest argument for tying a session to a specific business metric?", c: ["It makes the session easier to sell", "It lets you scope content and prove the outcome afterwards", "It is required by most training standards", "It shortens the preparation time needed"], a: [1], e: "The metric does two jobs: it tells you what to include and exclude, and it gives you something to measure against afterwards." },

    { d: "prep", x: 2, s: "You have been asked to train 40 customer-service agents on a new ticket pipeline. Which preparation step gives you the most useful information?", c: ["Reviewing the full feature documentation for the pipeline", "Interviewing a handful of agents about how they work today", "Building the slide deck early so there is time for revisions", "Asking the client which features they want covered"], a: [1], e: "Talking to actual learners tells you their current skill level, real workflow and anxieties — none of which the documentation or the sponsor's feature list will reveal." },
    { d: "prep", x: 2, s: "A stakeholder describes success as 'the team being more confident with HubSpot'. What should you do?", c: ["Accept it, since confidence is a legitimate training outcome", "Design the session and measure confidence with a post-session survey", "Work with them to translate it into an observable behaviour", "Decline the engagement as the brief is unclear"], a: [2], e: "Confidence cannot be scoped against or demonstrated. Converting it into something observable — 'every rep builds and enrols a sequence unaided' — makes it both designable and provable." },
    { d: "prep", x: 3, s: "Pre-work was assigned but you learn a day before that fewer than half the group completed it. What is the best response?", c: ["Postpone the session until everyone has completed it", "Deliver as planned and let those who skipped it catch up", "Adjust so the session works without pre-work, using it as a bonus for those who did", "Spend the first twenty minutes covering the pre-work content"], a: [2], e: "Designing so pre-work is an advantage rather than a dependency protects the session. Re-teaching it punishes the prepared and postponing rarely fixes completion rates." },
    { d: "prep", x: 2, s: "Which item is most likely to derail a live-portal demo?", c: ["A slightly outdated slide template", "Missing permissions on the training portal", "An agenda that runs five minutes long", "A participant joining late"], a: [1], e: "Permissions are the classic silent failure — everything looks fine until the moment you try to show the thing the session is about." },
    { d: "prep", x: 2, s: "You have 90 minutes and enough material for three hours. What is the best approach?", c: ["Deliver at a faster pace to fit it all in", "Cut to what serves the agreed objectives and protect the practice time", "Cover everything at a high level and provide detail as a handout", "Extend the session and ask the client for more time"], a: [1], e: "Scoping to the agreed objectives is the only cut that is defensible. Speeding up and skimming both reduce the session to exposure without practice." },
    { d: "prep", x: 3, s: "The sponsor wants a single session for both new hires and five-year veterans. What is the strongest recommendation?", c: ["Run one session pitched at the middle of the group", "Split into two sessions or two tracks by current skill level", "Run one session and let veterans leave early", "Pitch to the new hires and ask veterans to assist"], a: [1], e: "A single session pitched at the middle bores one half and loses the other. Splitting by level is the honest answer, and asking veterans to assist can supplement it but does not solve the mismatch alone." },
    { d: "prep", x: 2, s: "What is the main purpose of agreeing success criteria in writing before design begins?", c: ["To satisfy procurement requirements", "To anchor scope and give you something to evaluate against", "To reduce the number of stakeholder meetings", "To justify the fee if the session goes badly"], a: [1], e: "Written criteria fix what is in and out of scope and give the post-session evaluation something to compare against. The defensive uses are secondary." },
    { d: "prep", x: 2, s: "Which of these is a preparation activity rather than a content-creation activity?", c: ["Writing the exercise instructions", "Building the practice sandbox data", "Interviewing the sales manager about pipeline problems", "Designing the slide template"], a: [2], e: "Interviewing to understand the problem and the audience is preparation. The other three are all building materials, which comes after preparation tells you what to build." },
    { d: "prep", x: 3, s: "During preparation you discover the client's real problem is that two teams disagree on lead qualification. What is the most professional response?", c: ["Deliver the requested HubSpot training anyway, as scoped", "Report the finding and propose addressing the definition first", "Add a slide about lead qualification to the session", "Decline the engagement"], a: [1], e: "Naming what you found is the value of doing a needs assessment. Training a disputed process into two teams entrenches the disagreement rather than resolving it." },

    { d: "create", x: 2, s: "You are designing a 60-minute session with one objective: build a lead-nurturing sequence. In what order should you design?", c: ["Slides, then exercise, then objective check", "Objective, then practice exercise, then supporting content", "Content outline, then slides, then an exercise if time allows", "Agenda, then slides, then handout"], a: [1], e: "Backwards design fixes the practice before content can expand into its time. 'An exercise if time allows' is how practice reliably disappears." },
    { d: "create", x: 2, s: "A colleague's slides are dense enough to read on their own. What is the main problem?", c: ["They will take too long to build", "They compete with the trainer for attention and are hard to present from", "They will not print well", "They are unlikely to be accessible"], a: [1], e: "A slide readable on its own makes the audience read rather than listen. Dense reference material belongs in a handout or job aid instead." },
    { d: "create", x: 2, s: "What is the strongest reason to use the client's own data in exercises?", c: ["It reduces the time needed to build the exercise", "It transfers directly to the learner's real work", "It avoids licensing issues with demo data", "It makes the session look more customised"], a: [1], e: "Recognisable data means the practice rehearses the actual Monday-morning task. Looking customised is a side effect, not the reason." },
    { d: "create", x: 3, s: "A learner completes a guided walkthrough successfully but cannot repeat it alone ten minutes later. What is most likely missing from the design?", c: ["A more detailed handout", "An independent practice step after the guided one", "A longer demonstration", "A knowledge-check quiz"], a: [1], e: "Following along is recognition, not recall. The ramp needs a supported and then an independent attempt before you can claim the objective was met." },
    { d: "create", x: 2, s: "Which is the best use of a job aid?", c: ["Summarising the slides for people who missed the session", "Supporting the task at the moment of work afterwards", "Providing a reading list for further learning", "Recording attendance and completion"], a: [1], e: "A job aid is a point-of-work reference — a checklist or decision tree used while doing the task. Session summaries serve a different purpose." },
    { d: "create", x: 2, s: "Which change most improves accessibility of training materials?", c: ["Using more images instead of text", "Highlighting required fields in red only", "Ensuring contrast, readable type and captions on video", "Adding animation to draw attention to key points"], a: [2], e: "Contrast, type size and captions address the most common access barriers. Colour alone — the red-only option — actively excludes colour-blind learners, and animation can hinder rather than help." },
    { d: "create", x: 3, s: "You must cut fifteen minutes from a designed session. What should go first?", c: ["The hands-on exercise", "A content section not tied to a stated objective", "The closing and next steps", "The opening relevance framing"], a: [1], e: "Content not serving an objective is the only genuinely optional part. Cutting the exercise removes what changes behaviour, and cutting the open or close removes relevance and follow-through." },
    { d: "create", x: 2, s: "Why should training materials carry a version and date?", c: ["To support invoicing and time tracking", "Because product interfaces change and stale screenshots undermine credibility", "To meet accessibility standards", "To prevent unauthorised sharing"], a: [1], e: "SaaS interfaces move constantly. Versioning makes it visible when a screenshot is out of date, before a learner points it out mid-session." },
    { d: "create", x: 2, s: "How long should a content chunk run before something is asked of the learner?", c: ["Around 5 minutes", "Around 10–15 minutes", "Around 30 minutes", "Until the topic is complete, however long that takes"], a: [1], e: "Ten to fifteen minutes is the practical block before attention degrades. 'Until the topic is complete' is how sessions become lectures." },

    { d: "deliver", x: 2, s: "You ask 'does that make sense?' and the room nods. What has this told you?", c: ["The explanation was clear", "Nothing reliable about their understanding", "That you can move on safely", "That the pace is correct"], a: [1], e: "A closed question invites a nod. Only asking someone to do, explain or predict something produces evidence of understanding." },
    { d: "deliver", x: 2, s: "You ask a question in a virtual session and get silence. What is the best next move?", c: ["Answer it yourself and move on", "Wait about five seconds, then invite a specific person by name", "Repeat the question more slowly", "Move to a different topic to avoid awkwardness"], a: [1], e: "Silence feels far longer at the front than in the room, and a named invitation converts a broadcast question into an answerable one." },
    { d: "deliver", x: 3, s: "One participant answers every question before anyone else can. What is the best intervention?", c: ["Ask them privately at the break to contribute less", "Introduce a write-first-then-share or round-robin structure", "Avoid making eye contact with them", "Thank them and explicitly ask others to speak instead"], a: [1], e: "Structure redistributes airtime without singling anyone out or relying on a private conversation. Direct requests can work but risk disengaging a willing participant." },
    { d: "deliver", x: 2, s: "A learner asks a question you cannot answer. What is the best response?", c: ["Offer your best guess with a caveat", "Say you do not know and commit to following up by a stated time", "Redirect the question to the group", "Explain that it is outside the scope of the session"], a: [1], e: "Admitting the gap with a concrete follow-up protects credibility. A guess in front of people who can verify it costs far more than the admission would have." },
    { d: "deliver", x: 2, s: "Halfway through, you realise you are fifteen minutes behind. What should you cut?", c: ["The hands-on exercise, and demonstrate it instead", "A content section, protecting the practice time", "The closing and next steps", "The question-and-answer time"], a: [1], e: "The exercise is what changes behaviour and the close is what makes it stick afterwards. Content is the compressible part." },
    { d: "deliver", x: 3, s: "A participant is visibly disengaged throughout. Before addressing it as an attitude problem, what should you check?", c: ["Whether they have the technical prerequisites", "Whether the content is relevant to their role and whether they chose to attend", "Whether they are having connection problems", "Whether they have attended similar training before"], a: [1], e: "Irrelevance and mandated attendance explain far more disengagement than attitude does, and both are addressable. The other checks are worth doing but are less commonly the cause." },
    { d: "deliver", x: 2, s: "How frequently should a virtual session include an interaction?", c: ["Once at the start and once at the end", "Roughly every five minutes", "Roughly every twenty minutes", "Only when learners ask questions"], a: [1], e: "Virtual attention decays much faster than in a room, and a five-minute rhythm of polls, chat prompts or named questions is what holds it." },
    { d: "deliver", x: 2, s: "An off-topic but genuinely useful question comes up thirty minutes in. What is the best handling?", c: ["Answer it fully, since it is useful", "Park it visibly and commit to returning to it", "Explain that it is out of scope", "Ask the group whether they want to cover it"], a: [1], e: "Parking preserves both the agenda and the questioner's willingness to speak. Answering it fully derails the plan; dismissing it teaches the room not to ask." },
    { d: "deliver", x: 3, s: "You demo a workflow build at your normal working speed and learners look lost. What went wrong?", c: ["The workflow example was too complex", "Expert pace made the steps invisible; you did not narrate the decisions", "The screen share resolution was too low", "The learners lacked prerequisites"], a: [1], e: "Fluent expert execution hides the decision points. Slowing to first-attempt pace and narrating what you are choosing and why is what makes a demo teachable." },
    { d: "deliver", x: 2, s: "What is the most valuable element of a session close?", c: ["A summary of everything covered", "What happens next: job aid, reinforcement and who to ask", "A satisfaction survey", "Time for final questions"], a: [1], e: "A summary changes nothing on its own. Naming the follow-up and the support route is what carries the session into the learner's actual work." },
    { d: "deliver", x: 2, s: "Which opening is most likely to earn attention in the first two minutes?", c: ["A detailed overview of your background and credentials", "The problem the learners have and what will be different by the end", "A full walkthrough of the agenda", "An icebreaker unrelated to the topic"], a: [1], e: "The opening minutes are the most attentive of the session and should be spent on relevance. Credentials and agendas can come after, briefly." },
    { d: "deliver", x: 3, s: "In a breakout exercise, one group finishes in half the time. What is the best use of the remaining time?", c: ["Let them wait until the other groups finish", "Give them an extension task that stretches the same objective", "Bring the whole session back early", "Ask them to help the slower groups immediately"], a: [1], e: "A prepared extension keeps fast finishers engaged without rushing anyone else. Peer support can work but often means the fast group does the slow group's work for them." },

    { d: "impl", x: 2, s: "A client asks why a half-day session costs more than half a day of your time. What is the best explanation?", c: ["Training rates are higher than consulting rates", "The fee covers needs analysis, design and materials as well as delivery", "It reflects the value the training will create", "Preparation time is standard industry practice to bill"], a: [1], e: "Delivery is the visible tip of the work. Naming the analysis, design and materials explains the price with something concrete rather than an appeal to value or convention." },
    { d: "impl", x: 1, s: "Which of Kirkpatrick's levels does a post-session satisfaction survey measure?", c: ["Reaction", "Learning", "Behaviour", "Results"], a: [0], e: "Satisfaction is level one, reaction. Learning needs assessment, behaviour needs observation in the workplace, and results need a business metric." },
    { d: "impl", x: 3, s: "Three months after training, the client wants evidence it worked. Which is the strongest evidence?", c: ["Average satisfaction score from the session feedback form", "Percentage of attendees who passed the end-of-session quiz", "Change in logged sales activity in HubSpot against the pre-training baseline", "A follow-up survey asking whether attendees apply what they learned"], a: [2], e: "System data against a baseline is level-three behaviour evidence and is not self-reported. The quiz is level two, and both survey options are self-report at best." },
    { d: "impl", x: 2, s: "Why does a baseline measurement matter?", c: ["It helps set the training agenda", "Without a before-measure, an after-measure proves nothing", "It is required for Kirkpatrick level one", "It identifies which learners need extra support"], a: [1], e: "Attribution requires a comparison point. An impressive post-training number is meaningless if nobody recorded what it was beforehand." },
    { d: "impl", x: 2, s: "Which item most belongs in an explicit out-of-scope list?", c: ["The number of attendees", "Unlimited revisions to materials after delivery", "The session objectives", "The delivery format"], a: [1], e: "Out-of-scope statements exist to bound open-ended commitments. Attendees, objectives and format are all in-scope items that should be specified rather than excluded." },
    { d: "impl", x: 3, s: "A client wants a single training session to drive lasting CRM adoption. What should you recommend?", c: ["A longer single session covering more ground", "A session plus reinforcement: job aids, follow-up and an adoption plan", "Recording the session so people can rewatch it", "Repeating the same session quarterly"], a: [1], e: "Behaviour reverts within weeks without reinforcement. Length, recordings and repetition all deliver more exposure but none of them provide the ongoing support that sustains adoption." },
    { d: "impl", x: 2, s: "Why should training materials be treated as a maintained asset?", c: ["To justify ongoing retainer fees", "Because product interfaces change and outdated materials lose credibility", "To comply with certification requirements", "Because learners request updated copies"], a: [1], e: "SaaS products change continuously, so materials decay whether or not anyone maintains them. Pricing and scheduling that maintenance keeps them usable." },
    { d: "impl", x: 2, s: "Which measure best represents Kirkpatrick level four?", c: ["Attendees can describe the new process", "Attendees are using the new process in HubSpot", "Sales cycle length has shortened since the change", "Attendees rated the session highly"], a: [2], e: "Level four is business results. Describing is level two, using it is level three behaviour, and ratings are level one." },
  ],
});
