/* HubSpot Revenue Operations.

   Written from HubSpot Academy's published course outline for the Revenue
   Operations certification: alignment across marketing, sales and service;
   process design and waste elimination; data as a single source of truth;
   measurement and forecasting; and the team and hiring side of running RevOps.

   All items are original. Domain weightings are inferred from the relative
   depth of the published lessons — HubSpot does not publish a numeric blueprint
   for this exam. */

window.CERT_COURSES.push({
  id: "hubspot-revops",
  built: "2026-08-02",
  cert: {
    code: "REVOPS",
    name: "HubSpot Revenue Operations",
    vendor: "HubSpot Academy",
    blurb: "Aligning marketing, sales and service around one process, one data set and one set of numbers.",
  },
  weightsNote: "HubSpot does not publish a numeric blueprint for this exam. These weights are inferred from the relative depth of the published lessons — treat the split as approximate.",
  exam: {
    questionCount: 60,
    timeLimitMin: 180,
    passMode: "raw",
    passValue: 45,
    scaledMax: 0,
    multiSelect: false,
    note: "60 questions, 45 correct to pass. 3-hour limit, ~1 hour expected. 12-hour lockout between attempts.",
  },

  domains: [
    {
      id: "align",
      name: "Foundations and Alignment",
      weight: 0.20,
      summary: "What revenue operations is, why the function exists, and how it aligns the goals, processes and technology of marketing, sales and customer success around one customer journey.",
      keyPoints: [
        "RevOps exists because marketing, sales and service optimising separately produces a worse whole. It owns the seams, not the departments.",
        "The flywheel replaces the funnel: customers are an input to growth, not an output of it, and friction is the thing to remove.",
        "Alignment has three legs — goals, process and systems. Fixing one without the others does not hold.",
        "A shared definition of a qualified lead, agreed in writing between marketing and sales, prevents most handoff disputes.",
        "An SLA in both directions: marketing commits to volume and quality, sales commits to follow-up speed and disposition.",
        "One revenue number that all three teams are measured against beats three departmental numbers that can all be met while revenue falls.",
        "RevOps is a service function with internal customers. Its output is other teams' throughput.",
        "Centralised, decentralised or hybrid — the model matters less than clear ownership of each process and system.",
      ],
      objectives: [
        "Explain the purpose and scope of revenue operations",
        "Apply the flywheel model to reduce friction",
        "Align goals, processes and systems across teams",
        "Define handoffs, qualification and bidirectional SLAs",
      ],
    },
    {
      id: "process",
      name: "Process Design and Optimisation",
      weight: 0.22,
      summary: "Defining the sales process, mapping it, finding where it leaks, and removing waste. Includes the Lean view of waste and the discipline of measuring before changing.",
      keyPoints: [
        "A sales process is defined by buyer actions, not seller optimism. Stages should have exit criteria you can verify.",
        "Every stage needs an objective definition — what must be true to leave it — or forecasting becomes fiction.",
        "Lean's waste categories: overproduction, waiting, transport, over-processing, inventory, motion, defects, and unused talent.",
        "In revenue terms, waste is duplicate data entry, waiting on approvals, leads sitting unworked, and reports nobody reads.",
        "Map the process as it actually runs before you map how it should run. The gap between them is usually the finding.",
        "Find the bottleneck first. Improving anything other than the constraint does not increase throughput.",
        "Measure the baseline before changing anything, or you cannot tell whether the change helped.",
        "Automate a good process; automating a broken one produces broken outcomes faster.",
        "Conversion rate between stages, and time in stage, are the two diagnostics that locate most leaks.",
      ],
      objectives: [
        "Define sales stages with verifiable exit criteria",
        "Map current-state process and identify waste",
        "Locate and relieve the constraint",
        "Baseline, change, and measure the effect",
      ],
    },
    {
      id: "data",
      name: "Data and Systems",
      weight: 0.20,
      summary: "Building a single source of truth: the data model, property design, integration between systems, data quality, and the governance that stops it degrading.",
      keyPoints: [
        "A single source of truth is a decision about which system wins for each object, not a claim that data lives in one place.",
        "The CRM object model — contacts, companies, deals, tickets — and the associations between them carry the reporting.",
        "Every property needs an owner, a definition and a reason to exist. Unowned properties become unreliable within months.",
        "Prefer dropdowns and defined values over free text for anything you intend to report on.",
        "Required fields are a tax on the person entering data; only require what someone downstream genuinely uses.",
        "Deduplication and normalisation are ongoing operations, not a one-off migration task.",
        "Integrations need a defined direction of sync and a defined winner on conflict, agreed before go-live.",
        "Data quality decays continuously. Audit on a schedule rather than after a report goes wrong.",
        "Lifecycle stage and lead status answer different questions: where they are in the journey versus what is being done about them.",
      ],
      objectives: [
        "Design a coherent CRM data model and property set",
        "Establish a single source of truth across systems",
        "Maintain data quality through governance",
        "Configure integrations with clear sync rules",
      ],
    },
    {
      id: "measure",
      name: "Measurement and Forecasting",
      weight: 0.22,
      summary: "Turning the data into decisions: the metrics that matter, funnel and lifecycle reporting, attribution, dashboards people act on, and forecasts that hold up.",
      keyPoints: [
        "Leading indicators predict, lagging indicators confirm. A dashboard of only lagging metrics tells you the quarter is lost too late.",
        "Conversion rate between each lifecycle stage is the diagnostic that localises a revenue problem.",
        "Forecast from stage conversion history and deal age, not from what reps say will close.",
        "Pipeline coverage compares open pipeline to target. Low coverage is a lead-generation problem, not a closing problem.",
        "Attribution models answer different questions — first touch measures what starts, last touch what finishes, multi-touch what contributes.",
        "Segment before concluding. An overall flat conversion rate can hide one segment collapsing and another improving.",
        "A metric without an owner and a decision attached to it is a vanity metric, however precise.",
        "Cohort analysis separates 'we got worse' from 'we got bigger', which raw period-over-period numbers cannot.",
        "Report on the same definitions every team agreed to; two teams with two definitions of a qualified lead cannot be reconciled afterwards.",
      ],
      objectives: [
        "Choose leading and lagging metrics deliberately",
        "Diagnose revenue problems through funnel conversion",
        "Build forecasts from historical conversion",
        "Apply attribution models to the right questions",
      ],
    },
    {
      id: "team",
      name: "Team, Enablement and Change",
      weight: 0.16,
      summary: "The human side: how the RevOps function is structured, hiring for it, enabling the teams it serves, and getting change adopted rather than resisted.",
      keyPoints: [
        "RevOps hires blend systems thinking, data literacy and enough business context to know which problems matter.",
        "Define ownership explicitly: who owns each system, each process and each number. Ambiguity here causes most operational failure.",
        "Enablement is what makes a process change stick; a process change announced but not enabled reverts.",
        "Involve the people who use a process in redesigning it — adoption is built during design, not after launch.",
        "Compensation drives behaviour more reliably than training does. Check the comp plan before blaming adoption.",
        "Change needs a named reason, a visible sponsor and a date. Without all three it is treated as optional.",
        "Document the process where the work happens, not in a wiki nobody opens.",
        "Measure adoption in the system, then coach the individuals the data identifies.",
      ],
      objectives: [
        "Structure a RevOps function and assign ownership",
        "Hire and enable for revenue operations",
        "Drive adoption of process and system change",
        "Align incentives with intended behaviour",
      ],
    },
  ],

  cards: [
    { d: "align", x: 1, f: "Why does revenue operations exist as a function?", b: "Because marketing, sales and service each optimising their own numbers produces a worse whole. RevOps owns the seams between them." },
    { d: "align", x: 2, f: "How does the flywheel differ from the funnel?", b: "A funnel treats customers as output; a flywheel treats them as an input to further growth. The work shifts from filling the top to removing friction throughout." },
    { d: "align", x: 2, f: "What are the three legs of alignment?", b: "Goals, process and systems. Aligning goals without changing the process, or the process without the systems, does not hold beyond the first quarter." },
    { d: "align", x: 2, f: "What is a bidirectional SLA?", b: "Marketing commits to lead volume and quality; sales commits to follow-up speed and disposition of every lead. One-way SLAs get ignored." },
    { d: "align", x: 3, f: "Why does a shared qualified-lead definition matter so much?", b: "Without one, marketing and sales report different numbers from the same events and neither can be reconciled afterwards. It is the single most common source of handoff conflict." },
    { d: "align", x: 2, f: "What is the argument for one shared revenue number?", b: "Three departmental targets can all be met in a quarter where revenue falls. A shared number makes trade-offs between teams visible." },
    { d: "align", x: 3, f: "Who are RevOps' customers?", b: "The internal revenue teams. Its output is their throughput, which is why it is judged on their results rather than on its own activity." },
    { d: "align", x: 2, f: "Centralised or decentralised RevOps?", b: "Either works. What matters is that every process and system has one named owner — ambiguous ownership causes more failure than the model does." },

    { d: "process", x: 2, f: "What should define a sales stage?", b: "A verifiable buyer action with objective exit criteria, not the rep's confidence. 'Demo delivered and next step booked' is a stage; 'interested' is not." },
    { d: "process", x: 2, f: "What are Lean's waste categories?", b: "Overproduction, waiting, transport, over-processing, inventory, motion, defects — and unused talent. In revenue work these show up as duplicate entry, approval queues and unworked leads." },
    { d: "process", x: 3, f: "Why map the current state before the future state?", b: "The gap between how the process is documented and how it actually runs is usually the finding. Designing from the documented version fixes a process nobody follows." },
    { d: "process", x: 2, f: "Why find the bottleneck first?", b: "Throughput is set by the constraint. Improving any other step adds work in progress without adding output." },
    { d: "process", x: 2, f: "What happens when you automate a broken process?", b: "You get broken outcomes faster and at greater scale. Fix the process, then automate it." },
    { d: "process", x: 2, f: "Which two diagnostics locate most pipeline leaks?", b: "Conversion rate between stages and time in stage. A collapse in one stage's conversion, or a stage where deals age, localises the problem." },
    { d: "process", x: 3, f: "Why baseline before changing a process?", b: "Without a before-measurement you cannot attribute any improvement to the change — or notice that it made things worse." },
    { d: "process", x: 2, f: "What is over-processing in a sales context?", b: "Work that adds no value to the buyer: approval steps nobody reads, fields nobody reports on, and reviews that never change a decision." },

    { d: "data", x: 2, f: "What does a single source of truth actually mean?", b: "A decision about which system wins for each object and field, not a claim that all data lives in one place." },
    { d: "data", x: 2, f: "What carries reporting in a CRM data model?", b: "The objects — contacts, companies, deals, tickets — and crucially the associations between them. Broken associations break reporting silently." },
    { d: "data", x: 2, f: "What does every property need?", b: "An owner, a definition and a reason to exist. Properties without all three become unreliable within months and pollute every report that touches them." },
    { d: "data", x: 2, f: "Why prefer dropdowns to free text?", b: "Anything you intend to report on needs defined values. Free text produces twelve spellings of the same answer and no usable segmentation." },
    { d: "data", x: 3, f: "When should a field be required?", b: "Only when someone downstream genuinely uses it. Required fields are a tax on the person entering data and produce junk values when the tax is too high." },
    { d: "data", x: 2, f: "What must be agreed before an integration goes live?", b: "The direction of sync per field and which system wins on conflict. Deciding this after go-live means reconciling data that has already diverged." },
    { d: "data", x: 3, f: "Lifecycle stage versus lead status — what is the difference?", b: "Lifecycle stage is where someone is in the journey; lead status is what is currently being done about them. Collapsing them into one property loses both answers." },
    { d: "data", x: 2, f: "Why audit data quality on a schedule?", b: "Quality decays continuously through imports, integrations and human entry. Auditing only after a report looks wrong means acting on bad data in the meantime." },
    { d: "data", x: 2, f: "Is deduplication a project or an operation?", b: "An operation. New duplicates arrive with every form fill, import and integration sync, so a one-off cleanup regresses within weeks." },

    { d: "measure", x: 2, f: "Leading versus lagging indicators?", b: "Leading indicators predict — meetings booked, pipeline created. Lagging indicators confirm — closed revenue. A dashboard of only lagging metrics reports the loss too late to act." },
    { d: "measure", x: 2, f: "How should a forecast be built?", b: "From historical stage-conversion rates and deal age, not from rep confidence. Reps forecast optimism; history forecasts outcomes." },
    { d: "measure", x: 2, f: "What does pipeline coverage tell you?", b: "Open pipeline against target. Low coverage is a top-of-funnel problem and cannot be closed by better closing." },
    { d: "measure", x: 3, f: "When is first-touch attribution the right model?", b: "When the question is what starts opportunities — which channels create demand. It is the wrong model for judging what closes it." },
    { d: "measure", x: 3, f: "Why segment before drawing a conclusion?", b: "An overall flat conversion rate can hide one segment collapsing and another improving. Aggregates conceal exactly the movement worth acting on." },
    { d: "measure", x: 2, f: "What makes a metric a vanity metric?", b: "No owner and no decision attached to it. Precision does not rescue a number nobody would act on." },
    { d: "measure", x: 3, f: "What does cohort analysis separate?", b: "'We got worse' from 'we got bigger'. Period-over-period totals mix the two; cohorts hold acquisition date constant." },
    { d: "measure", x: 2, f: "Why do two teams' reports disagree?", b: "Almost always because they use different definitions of the same term. Reconciling reports after the fact is impossible without first reconciling definitions." },

    { d: "team", x: 2, f: "What do you hire for in RevOps?", b: "Systems thinking, data literacy and enough business context to know which problems are worth solving. Tool expertise is the easiest of the three to teach." },
    { d: "team", x: 2, f: "Why does explicit ownership matter?", b: "Every system, process and number needs one named owner. Ambiguous ownership causes more operational failure than any choice of org model." },
    { d: "team", x: 3, f: "Why does a process change revert?", b: "Because it was announced rather than enabled. Without training, job aids and reinforcement, people return to the method they already know." },
    { d: "team", x: 3, f: "Why check the comp plan before blaming adoption?", b: "Compensation drives behaviour more reliably than training does. If the plan rewards the old behaviour, no amount of enablement will change it." },
    { d: "team", x: 2, f: "What does a change need to be taken seriously?", b: "A named reason, a visible sponsor and a date. Missing any of the three and it is treated as optional." },
    { d: "team", x: 2, f: "Where should a process be documented?", b: "Where the work happens — in the CRM, the playbook, the task template. A wiki nobody opens is documentation in name only." },
    { d: "team", x: 2, f: "How should adoption be managed?", b: "Measure it in the system, then coach the specific individuals the data identifies. Broadcasting a reminder to everyone addresses nobody." },
  ],

  questions: [
    { d: "align", x: 2, s: "Marketing hit its MQL target, sales hit its activity target, and service hit its CSAT target — but revenue fell short. What does this most strongly suggest?", c: ["The targets were set too low", "The teams are optimising separate metrics that do not add up to revenue", "Sales did not work the leads marketing generated", "The market conditions changed"], a: [1], e: "Three departmental targets being met while revenue falls is the defining symptom RevOps exists to fix. The other options may contribute but the structural issue is the metric design." },
    { d: "align", x: 2, s: "What is the main practical consequence of adopting the flywheel model over the funnel?", c: ["More budget moves to top-of-funnel marketing", "Existing customers become an input to growth and friction becomes the target", "Sales and marketing merge into a single team", "The pipeline stages are renamed"], a: [1], e: "The flywheel treats customers as a source of further growth rather than an endpoint, so the work becomes removing friction across the whole journey." },
    { d: "align", x: 3, s: "Sales says the leads are poor; marketing says sales does not work them. Both have data. What is the most likely root cause?", c: ["Sales needs better training on lead follow-up", "Marketing needs to raise its lead quality threshold", "The two teams are using different definitions of a qualified lead", "The CRM is not capturing follow-up activity correctly"], a: [2], e: "When both sides have data supporting opposite conclusions, they are usually measuring different things. Agreeing one written definition has to come before either operational fix." },
    { d: "align", x: 2, s: "Which is the best example of a bidirectional SLA?", c: ["Marketing commits to 500 MQLs per month", "Sales commits to contacting every lead within one hour", "Marketing commits to 500 qualified MQLs and sales commits to contacting each within one hour and dispositioning it", "Both teams commit to a shared revenue target"], a: [2], e: "A bidirectional SLA binds both sides with specific, checkable commitments. Either half alone leaves the other free to blame it, and a shared target is alignment but not an SLA." },
    { d: "align", x: 2, s: "A company is deciding between a centralised and a decentralised RevOps team. Which consideration matters most?", c: ["Which model the largest competitors use", "Whether every process and system has one clear owner", "The total headcount available", "Whether the CRM supports team-based permissions"], a: [1], e: "Both models work in practice. Clear ownership of each process and system is what actually determines whether operations hold together." },
    { d: "align", x: 3, s: "Which best describes the output of a RevOps function?", c: ["Reports and dashboards", "The throughput of the revenue teams it serves", "CRM configuration and integrations", "Process documentation"], a: [1], e: "Reports, configuration and documentation are activities. RevOps is judged on whether the revenue teams perform better, which is why it is a service function with internal customers." },

    { d: "process", x: 2, s: "Which of these is a properly defined sales stage?", c: ["Interested", "Qualified", "Demo delivered and next meeting booked", "Hot prospect"], a: [2], e: "Only the third names a verifiable buyer action with objective exit criteria. The others describe seller sentiment, which cannot be audited or forecast from." },
    { d: "process", x: 3, s: "Reps re-enter the same customer data into the CRM and then into the quoting tool. In Lean terms this is primarily which waste?", c: ["Waiting", "Overproduction", "Over-processing and defects", "Motion"], a: [2], e: "Duplicate entry is work that adds nothing for the buyer and reliably introduces discrepancies between systems — over-processing that generates defects." },
    { d: "process", x: 2, s: "Analysis shows deals convert well through every stage except proposal-to-close, where conversion halves. Where should effort go first?", c: ["Generating more leads to compensate", "Improving the earlier stages so more deals reach proposal", "Investigating what happens at proposal-to-close", "Shortening the overall sales cycle"], a: [2], e: "That stage is the constraint. Adding volume upstream pushes more deals into the same bottleneck without increasing closed revenue." },
    { d: "process", x: 3, s: "A team is about to automate its lead-routing process, which currently misassigns about a fifth of leads. What should happen first?", c: ["Automate it, since automation will reduce human error", "Fix the routing logic before automating it", "Automate it and monitor the error rate afterwards", "Add a manual review step after the automation"], a: [1], e: "Automating a process that misassigns leads produces misassignment faster and at greater scale. The logic has to be right before it is made automatic." },
    { d: "process", x: 2, s: "Why map the current-state process before designing the future state?", c: ["It is required for process certification", "The gap between documented and actual process is usually where the problem is", "It gives the team something to review", "It makes the future-state map faster to draw"], a: [1], e: "People follow the real process, not the documented one. Designing from documentation produces an improvement to a process nobody was using." },
    { d: "process", x: 2, s: "A change to the qualification criteria is rolled out with no baseline measurement. Three months later conversion is up. What can be concluded?", c: ["The change caused the improvement", "The change did not cause the improvement", "Nothing can be attributed to the change with confidence", "The improvement is within normal variance"], a: [2], e: "Without a before-measure there is no basis for attribution. The improvement might be seasonal, market-driven, or caused by something else entirely." },
    { d: "process", x: 2, s: "Deals are sitting an average of 40 days in one stage against 8 days in every other. What does this most likely indicate?", c: ["That stage requires more work by nature", "A bottleneck or unclear exit criteria at that stage", "Reps are neglecting their pipeline hygiene", "The stage should be removed"], a: [1], e: "Time in stage is a leak diagnostic. A stage where deals age is either genuinely constrained or has criteria vague enough that nobody knows when to move a deal on." },
    { d: "process", x: 3, s: "Which is the clearest example of Lean 'waiting' waste in a revenue process?", c: ["A field on the deal record that nobody reports on", "Leads that sit unassigned over a weekend", "Reps logging activity in two systems", "A dashboard nobody opens"], a: [1], e: "Waiting is time in which nothing progresses. The unused field is over-processing, duplicate logging is over-processing with defects, and the unread dashboard is overproduction." },

    { d: "data", x: 2, s: "Marketing's automation platform and the CRM both hold job title, and they disagree. What is the correct first step?", c: ["Overwrite the CRM values from the marketing platform", "Decide which system is authoritative for that field and configure the sync accordingly", "Make job title read-only in both systems", "Delete the field from one system"], a: [1], e: "A single source of truth is a per-field decision about which system wins. Overwriting without deciding just moves the discrepancy in one direction." },
    { d: "data", x: 2, s: "A company wants to report on industry but the property is free text and contains hundreds of variations. What is the underlying design mistake?", c: ["The property was not made required", "A reportable field was left as free text rather than defined values", "Too many people had permission to edit it", "The property was created on the wrong object"], a: [1], e: "Anything intended for reporting needs a constrained value set. Free text guarantees unsegmentable data regardless of who edits it or whether it is required." },
    { d: "data", x: 3, s: "A sales manager asks for eight new required fields on the deal record so reporting is complete. What is the strongest response?", c: ["Add them, since complete data supports better decisions", "Add them but make them optional", "Ask which downstream decision each field will change, and require only those", "Refuse, as required fields reduce adoption"], a: [2], e: "Required fields are a tax on the person entering data and produce junk when the tax is too high. Tying each to an actual decision is what separates useful requirements from wish lists." },
    { d: "data", x: 2, s: "What is the difference between lifecycle stage and lead status?", c: ["They are alternative names for the same concept", "Lifecycle stage is where someone is in the journey; lead status is what is being done about them", "Lifecycle stage is set by marketing; lead status by sales", "Lifecycle stage applies to contacts; lead status to companies"], a: [1], e: "They answer different questions and are both needed. Ownership tends to differ too, but that is a consequence rather than the defining distinction." },
    { d: "data", x: 3, s: "After a clean deduplication project, duplicates return within two months. What was the mistake?", c: ["The deduplication rules were too narrow", "Treating deduplication as a project rather than an ongoing operation", "The import that created them was not reversed", "Users were not trained on searching before creating"], a: [1], e: "Forms, imports and integrations create new duplicates continuously. A cleanup with no ongoing process necessarily regresses." },
    { d: "data", x: 2, s: "Two systems are being integrated. Which decision is most important to make before go-live?", c: ["Which fields to map", "The sync direction per field and which system wins on conflict", "How often the sync runs", "Who has admin access to the integration"], a: [1], e: "Field mapping is necessary but conflict resolution is what prevents silently diverging data. Deciding it after go-live means reconciling records that have already drifted." },
    { d: "data", x: 2, s: "Which practice most reliably preserves data quality over time?", c: ["A large one-off cleanup before an important reporting cycle", "Scheduled audits with named owners for each property", "Restricting record creation to administrators", "Requiring more fields at the point of entry"], a: [1], e: "Quality decays continuously, so only a recurring process holds it. Restriction and required fields both create friction without addressing decay." },
    { d: "data", x: 3, s: "A report on deals by source returns far fewer records than expected. Which cause is most likely and most easily missed?", c: ["The report filter is wrong", "Missing associations between deals and the contacts carrying the source", "The source property was recently renamed", "Deleted records are excluded"], a: [1], e: "Associations carry reporting in a CRM object model, and broken ones fail silently — records simply do not appear rather than raising an error." },

    { d: "measure", x: 2, s: "A dashboard shows closed revenue, win rate and average deal size only. What is the main weakness?", c: ["It does not segment by team", "All three are lagging indicators, so problems surface too late to act on", "It lacks a comparison to target", "It does not show individual rep performance"], a: [1], e: "Lagging metrics confirm what already happened. Without leading indicators such as meetings booked or pipeline created, the quarter is diagnosed after it is lost." },
    { d: "measure", x: 3, s: "A sales leader forecasts from reps' own confidence ratings and has missed the number four quarters running. What is the strongest fix?", c: ["Require reps to justify each rating in writing", "Forecast from historical stage-conversion rates and deal age", "Reduce the number of confidence levels available", "Review each deal individually in a weekly meeting"], a: [1], e: "Rep confidence is systematically optimistic and does not improve with justification or review. Historical conversion is the evidence-based alternative." },
    { d: "measure", x: 2, s: "Pipeline coverage is 1.5x against a target of 3x. What does this indicate?", c: ["Deals are being lost too late in the cycle", "There is not enough pipeline being created", "Win rates have declined", "Deals are too small"], a: [1], e: "Coverage compares open pipeline to target, so a shortfall is a creation problem. No improvement in closing can compensate for pipeline that does not exist." },
    { d: "measure", x: 3, s: "You want to know which channels generate demand that eventually closes. Which attribution model best answers this?", c: ["Last touch", "First touch", "Linear multi-touch", "Time decay"], a: [1], e: "First touch measures what starts the journey, which is the demand-generation question. Last touch and time decay both weight the closing end." },
    { d: "measure", x: 3, s: "Overall lead-to-customer conversion is unchanged year on year, but the business feels worse. What analysis is most likely to reveal what is happening?", c: ["Extending the reporting period for more data", "Segmenting by source, size or region", "Recalculating with a different attribution model", "Comparing against industry benchmarks"], a: [1], e: "Aggregates conceal offsetting movements — one segment collapsing while another improves leaves the total flat. Segmentation is what surfaces it." },
    { d: "measure", x: 2, s: "Which of these is most clearly a vanity metric?", c: ["Meetings booked per rep per week", "Total website sessions, reported monthly with no owner", "Stage-to-stage conversion rate", "Average days to close"], a: [1], e: "The defining feature is that no decision hangs on it and nobody owns it. The other three each localise a problem or trigger an action." },
    { d: "measure", x: 3, s: "Retention appears to be falling, but the company has also grown quickly. What analysis separates the two effects?", c: ["Period-over-period comparison", "Cohort analysis by acquisition month", "Segmenting by product line", "Recalculating with a rolling average"], a: [1], e: "Cohorts hold acquisition date constant, which separates genuine deterioration from a changing mix of customer tenure. Period comparisons mix the two together." },
    { d: "measure", x: 2, s: "Marketing reports 400 qualified leads last month; sales reports 260. Both pulled from the same CRM. What is the first thing to check?", c: ["Whether the reports cover the same date range and definition", "Whether records were deleted between the two reports", "Whether sales has permission to see all records", "Whether the integration failed partway through the month"], a: [0], e: "Differing definitions and date ranges explain the overwhelming majority of these disputes, and no technical investigation is meaningful until definitions are reconciled." },

    { d: "team", x: 2, s: "Which combination best describes what to hire for in a RevOps role?", c: ["Deep expertise in the specific CRM in use", "Systems thinking, data literacy and business context", "Sales experience and strong relationship skills", "Project management certification and process documentation experience"], a: [1], e: "Tool expertise is the most teachable of these. The durable requirements are the ability to reason about systems, work with data, and judge which problems matter." },
    { d: "team", x: 3, s: "A new deal-stage process was announced by email and adoption is at 30% after a month. What was most likely missing?", c: ["A stricter enforcement policy", "Enablement: training, job aids and reinforcement", "Executive approval of the change", "A longer notice period before the change"], a: [1], e: "An announced change without enablement reverts to the method people already know. Enforcement without capability produces workarounds rather than adoption." },
    { d: "team", x: 3, s: "Reps are told to log every call, are trained on it, and still do not. Their commission depends entirely on closed revenue. What should be examined first?", c: ["The quality of the training", "Whether the logging process is too slow", "The compensation plan and what it rewards", "Whether managers are following up"], a: [2], e: "Compensation drives behaviour more reliably than training does. Process friction and management follow-up matter, but a plan that rewards nothing for logging is the structural cause." },
    { d: "team", x: 2, s: "What does a process change need to be treated as mandatory rather than optional?", c: ["Detailed documentation", "A named reason, a visible sponsor and a date", "Approval from every affected team", "A pilot group before full rollout"], a: [1], e: "Reason, sponsor and date together signal that the change is real. Documentation and pilots support execution but do not by themselves establish that it is happening." },
    { d: "team", x: 2, s: "Where should a new sales process be documented so it is actually followed?", c: ["In a shared wiki linked from the intranet", "In the CRM itself — playbooks, task templates and stage guidance", "In the onboarding handbook", "In the recording of the training session"], a: [1], e: "Documentation at the point of work is used; documentation someone must go and find is not. The others are supplementary references." },
    { d: "team", x: 3, s: "Adoption of a new workflow is at 60%. What is the most effective next step?", c: ["Send a reminder to the whole team", "Identify the specific non-adopters in the system data and coach them", "Extend the deadline for adoption", "Make the workflow mandatory through required fields"], a: [1], e: "A broadcast reminder addresses the 60% who already comply and nobody in particular. Targeting the individuals the data identifies is what moves the number." },
    { d: "team", x: 2, s: "When is the right time to involve the people who will use a process in designing it?", c: ["After the design is drafted, for feedback", "During the design, as participants", "At launch, during training", "After launch, to gather improvement suggestions"], a: [1], e: "Adoption is built during design. Consultation after the fact produces comments on a decision already made, which is why it rarely changes the outcome." },
  ],
});
